### ISSUE TITLE
New madoca correctio 

### ISSUE THREAD

**Issue by susilosarimun** [hirokawa/cssrlib#3]

**Comment by susilosarimun** [comment]
Dear Hirokawa;
It is possible to use this library to decode CSSR data from QZSS Madoca Correction

Thank you

Susilo

**Comment by hirokawa** [comment]
Madoca is broadcasting cssr, it can be decoded.

**Comment by susilosarimun** [comment]
Could I use this libraru to decode CSSR from Ublox raw?
Thank you

**Comment by hirokawa** [comment]
cssrlib is not directly supprting ubx binary, but, it is supporting broadcasting QZSS L6 message stream, QZSS L6 message packed in ubx binary should also be decoded.
